name: Build Debian Package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python (if needed)
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y devscripts debhelper

    - name: Build Debian package
      run: |
        debuild -us -uc -b